### ISSUE TITLE
IE11 seek issue

### ISSUE THREAD

**Issue by jonaswindey** [souporserious/react-media-player#11]
There's a problem when seeking on IE11 when the video is playing.

When the video is stopped, it's working perfectly.

```
_handleMouseDown = () => {
    this._isPlayingOnMouseDown = this.props.media.isPlaying
    //this.props.media.pause() -> when you comment this line, clicking on the progress bar works, but seeking by dragging doesn't
  }
```

It seems the value of the range slider isn't updated when we pause the media on mouseDown. 

I know you handle the value change in handleMouseUp to fix the known bug for range sliders on IE11, but pausing on mousedown seems to break the functionality when the media is playing.

**Comment by jonaswindey** [comment]
As a workaround I changed the input type="range" from Progress.jsx to https://github.com/whoisandie/react-rangeslider

**Comment by souporserious** [comment]
Since you are able to provide your own `SeekBar` component I'm going to close this issue. If you can find an elegant solution that doesn't require another library please feel free to create a PR.
