### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by karlguillotte** [souporserious/react-media-player#16]
I am noticing that it is been a while since a new release has not been published on npm and there are lots of fixes that have been pushed to this repo. Would it be possible to have a release on npm with all your fixes?

Thanks for sharing your code!

**Comment by souporserious** [comment]
Sorry about that! I've been super busy lately. I'll work on the docs this evening and push a new release :)

**Comment by souporserious** [comment]
Done :) https://github.com/souporserious/react-media-player/commit/de133a21f2569cd1f5080efe8b0fa117ce34fd44

**Comment by karlguillotte** [comment]
Amazing! Thank you.
