### ISSUE TITLE
Plans for To-do

### ISSUE THREAD

**Issue by oyeanuj** [souporserious/react-media-player#2]
The to-do list on the main page looks very promising! I was wondering what are your plans and timing around it looking like?

Thanks for creating this!

**Comment by souporserious** [comment]
Thank you :) I've been working on it for the past 6 months trying to figure out the best approach. I will update the README once I get everything in a place I like. I'll leave this open until then.

**Comment by souporserious** [comment]
Please refer [here](https://github.com/souporserious/react-media-player/issues/4) now for any requests and status on new features.
