### ISSUE TITLE
Server side rendering support

### ISSUE THREAD

**Issue by MikeDevice** [souporserious/react-media-player#26]
Now I'm getting a `ReferenceError: document is not defined` in several files. One of them is `request-fullscreen.js`
I can't even build project, bacause of this error.

**Comment by souporserious** [comment]
Sorry about that, I'm not too familiar with SSR environments. Any ideas on how to handle it? PR's are welcome :)

**Comment by oyeanuj** [comment]
@souporserious @MikeDevice Typically, these issues go away by just checking that `window` and `document` object are not undefined. In this library, I imagine in the fullscreen utils where the listeners are added, and any other place where `window` and `document` are being used need a check before those objects are used.
