### ISSUE TITLE
Changing Player size / proportions

### ISSUE THREAD

**Issue by MarkPare** [souporserious/react-media-player#30]
Great plugin.  Thank you for your work.

I'm trying to figure out how change size of player and scale video to fit.  My src is a video file (e.g. mp4) hosted on my own server.

Any suggestions?

**Comment by souporserious** [comment]
Thanks! :) are you trying to make it responsive? If so, I'd suggest looking at [this article](https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php) or [at this lib](http://fitvidsjs.com/).

**Comment by MarkPare** [comment]
Wow thank you for such a quick response.  I will look into those.  Thanks again for the great work.

**Comment by souporserious** [comment]
You're welcome :) please let me know if you have any other issues and I will try and help.

**Comment by abhikn** [comment]
the article doesnt help. i am just trying to resize the video so it could fit the screen. please offer detailed help
