### ISSUE TITLE
Does this player support live stream content

### ISSUE THREAD

**Issue by ceddyb** [souporserious/react-media-player#39]
E.g Audio live stream or Video live stream?

**Comment by souporserious** [comment]
I don't think so, but I would be willing to help with whatever and accept a PR for anything you need :)

**Comment by ceddyb** [comment]
It actually does, i figured you're using web audio api which supports it by default.

However most of the live stream servers like Shoutcast, keep throwing back a CORS error, i think it's due to my localhost origin, i'll try and play it outside localhost.
