### ISSUE TITLE
Clarify withMediaProps decorator usage

### ISSUE THREAD

**Issue by ismay** [souporserious/react-media-player#48]
This might be obvious to some, but it might be nice to clarify that components using the `withMediaProps` decorator only work when they're descendants of the `<Media>` component [here](https://github.com/souporserious/react-media-player#withmediaprops-decorator-props-exposed-under-thispropsmedia).

Just a line explaining that would already be enough I think.

**Comment by souporserious** [comment]
Sorry about that! I can definitely see how that can be confusing. I [updated the docs](https://github.com/souporserious/react-media-player/commit/dcb2f08eed5758766ccaa047b483b60d213afa16) to hopefully mitigate the confusion around this. I'm hoping to have a proper docs site sometime this year to help even more with this. Please feel free to open a PR if you'd like to add more clarification. Thanks for filing an issue!

**Comment by ismay** [comment]
Cool! 👍 Thanks for the quick fix and the awesome library!
