### ISSUE TITLE
How to customise Youtube player parameters.

### ISSUE THREAD

**Issue by NihilisticNive25** [souporserious/react-media-player#69]
I noticed that there are few default player parameters appended to the video URL. I require the option to customise this, like the **start** and **end** provided.

**Comment by souporserious** [comment]
There isn't a way to currently to do this, unfortunately 😞. I'm happy to help push through a PR if you want to add that functionality in! Probably best through something like a `config` prop.

**Comment by NihilisticNive25** [comment]
That is great! I have made some minor changes to configure YT params and raised a PR. Please review and merge.
