### ISSUE TITLE
DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by debotos** [souporserious/react-media-player#78]
How can I solve this error - Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

Sometimes because of it, the browser hangs.

**Comment by debotos** [comment]
Okay, I found the error. I was unintentionally calling media.playPause() function twice, that's why I was getting that exception.
After removing one function call it working without any exception.

**Comment by nabrahamson** [comment]
I am seeing this bug happen again with version 0.7.9. 

When seeking through an mp3 track, the component breaks and will no longer continue playing the audio file. If I assign a wav file to the component, it behaves as expected. 

```The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
<Original stack missing>```
